knp_snappy:
    pdf:
        enabled: true
        binary: '"C:\Program Files\wkhtmltopdf\bin\wkhtmltopdf.exe"' # Full path to the binary
        options:
            encoding: 'utf-8'
    image:
        enabled: true
        binary: '"C:\Program Files\wkhtmltopdf\bin\wkhtmltoimage.exe"' # Full path to the binary