
controllers:
    resource:
        path: ../src/Controller/
        namespace: App\Controller
    type: attribute

generate_qr:
    path: /generate-qr/{email}
    controller: App\Controller\QRCodeController::generateQrCode

scan_qr:
    path: /scan-qr
    controller: App\Controller\QRCodeController::scanQrCode
